[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
"probe-rs",
"run",
"--always-print-stacktrace",
"--chip", "STM32F103C8",
"--log-format", "{t} {L} {s}"
]

[build]
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "info"
